#! /usr/bin/env bash

echo  '--- dploy s3 bucket via cloud formation ---'

STACK_NAME='cloudformation-with-S3-simple'

aws cloudformation deploy \
    --template-file template.yaml \
    --no-execute-changeset \
    --stack-name $STACK_NAME \
    --region eu-west-3 