#! /usr/bin/env bash

echo "Creando un bucket de S3..."

if [ -z "$1" ]; then
    echo "Falta la variable nombre del bucket..."
    exit 1
fi

BUCKET_NAME=$1

aws s3api create-bucket \
 --bucket $BUCKET_NAME \
 --create-bucket-configuration LocationConstraint=eu-west-3 \
 --query Location \
 --output text